# Generated by Django 5.0.6 on 2024-07-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.AlterField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='users', to='findgame.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='games', to='findgame.category'),
        ),
    ]
