# Generated by Django 5.0.6 on 2024-07-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findgame', '0003_rename_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
