# Generated by Django 5.0.6 on 2024-07-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findgame', '0005_alter_game_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='keyFeatures',
            field=models.CharField(max_length=2000),
        ),
    ]
